docs/source/installation.rst
Suggest a stable PyPI release as default installation source instead of the git repo.
=> Suggest PyPI as recommended installation source

docs/source/getting-started.rst
When running the first monitor example from the Getting Started chapter, users would eventually get an error such as:
```
AttributeError: 'ItemCountMonitor' object has no attribute 'stats'
```
Arguably this could be fixed by replacing `self.stats` by `self.data.stats` or by using the `StatsMonitorMixin`. As this is a getting started section, this commit opted for the simpler solution (less objects to import, more explicit API).
=> Fix getting started example (AttributeError: 'ItemCountMonitor' object has no attribute 'stats')

docs/source/item-validation.rst, requirements.txt, tests/test_validators_jsonschema.py
After release of jsonschema 3.0.0, it is possible to validate data against draft6 and draft7. The keywords _exclusiveMinimum_ and _exclusiveMaximum_ changed in a backwards incompatible change which required an update in the existing tests.
=> Fix problem caused by backward incompatible change in jsonschema 3.0.0

docs/source/getting-started.rst
Fixed an error:
```
Traceback (most recent call last):
File "~/Code/quotesbot/quotesbot/monitors.py", line 9, in test_minimum_number_of_items
self.stats, 'item_scraped_count', 0)
AttributeError: 'ItemCountMonitor' object has no attribute 'stats'
```
=> Fixed an error with getting stats

setup.py
I propose to include `format` since it seems an obvious mistake that people use `format` and miss the dependencies.
The problem is if you have `format` validator and lack deps you won't get any error and probably will never know.
Related to #51
=> [+1 MRG] Update setup.py

docs/source/actions.rst, requirements.txt, setup.py
This should fix #158 . As slackclient version 1.3.* still works and the actual version don't work with Python lesser than 3.6, I didn't update the code to use newest version of the library. When spidermon become Python3.6+ only or the library stop working, we will need to change our action.
=> Slackclient version problem

docs/source/getting-started.rst
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
Import statement for `StatsMonitorMixin` missing in Getting started docs.
=> Add import statement in item validation docs

setup.py
Twisted 19.2.0 is the last Twisted version with Python 3.4 support.
=> Require Twisted<=19.2.0 for Python 3.4

docs/source/stats-collection.rst
This should improve docs of using stats history in Scrapy Cloud to avoid users having the problem of #186 .
=> docs: Improve stats history documentation

setup.py
lxml 4.4.0 dropped support for Python 3.4 and it is required by Scrapy package that is used by our tests, so while (this Scrapy issue)[https://github.com/scrapy/scrapy/issues/3912] is not fixed, we need this workaround to be able to execute Spidermon tests on Python 3.4.
=> Added constrain on lxml version based on Python version

docs/source/actions.rst, spidermon/contrib/actions/email/ses.py
The function `boto.connect_ses` does not allow the usage of a different region other than the default `us-east-1`.
With this commit it will be possible to set the AWS region by adding `SPIDERMON_AWS_REGION` to the settings.py.
=> feature: Add option to set AWS Region Name on SES E-Mail action

docs/source/item-validation.rst
-> path of validation models
referring to the sample code, so that the reader is not confused, I just modified this documentation,
=> docs: fix documentation example

spidermon/contrib/actions/slack/__init__.py, tests/contrib/actions/slack/test_slack_message_manager.py
This should help identifying problems like #207 .
Slack action needs a better error handling from API responses, but I believe this needs another PR.
=> feature: Log errors from Slack API calls

docs/source/conf.py, docs/source/getting-started.rst, docs/source/howto/index.rst, docs/source/howto/required-fields-coverage-validation.rst, docs/source/index.rst
This PR includes a how-to guide explaining how to use `ValidationMonitorMixin` together with the methods `check_missing_required_fields_percent` and `check_missing_required_fields` to validate minimum coverage of item fields considered as required.
=> docs: How-To Guide - Adding required fields coverage validation

spidermon/contrib/monitors/mixins/validation.py, tests/contrib/monitors/mixins/test_validation.py
=> bug: AttributeError when using ValidationMonitorMixin

docs/source/configuring-telegram-for-spidermon.rst
It is not possible to add [@userinfobot] to groups -> alternative: [@GroupIDbot]
It was not clear, that you need to add the info bot to the group to get the group id.
It was not clear, that you need to add your own bot to your group or (as admin) to your channel, to receive notifications in groups or channels.
=> docs: Including extra steps to iclude Telegram bot notifications in groups and channels

spidermon/contrib/actions/telegram/__init__.py, tests/contrib/actions/telegram/test_telegram_action.py
If the request sent to Telegram throw an error the following dict is returned: 
```
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}
```
Currently, Spidermon is calling the key `text` instead of `description` in order to add details to the logs, which is causing the following error:
```
ERROR: SendTelegramMessageSpiderFinished
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/ana/workspace/xxx/venv/lib/python3.8/site-packages/spidermon/core/actions.py", line 37, in run
self.run_action()
File "/home/ana/workspace/xxx/venv/lib/python3.8/site-packages/spidermon/contrib/actions/telegram/__init__.py", line 94, in run_action
File "/home/ana/workspace/xxx/venv/lib/python3.8/site-packages/spidermon/co …
```
=> bug: Fixed Telegram action error logging

docs/source/item-validation.rst
Looks like I've added a wrong example when writing this doc, which made the already confusing things even more confusing.
[The tests](https://github.com/scrapinghub/spidermon/blob/master/tests/contrib/monitors/mixins/test_validation.py#L214) show that the doc is wrong.
=> docs: Fix docs for check_*_percent field validation methods.

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/test_item_validation_monitor.py
It is common when using item validation pipelines to create a monitor that verifies if there are validation errors in the job results (`spidermon/validation/fields/errors` stat). This PR includes a basic monitor to be included in the basic monitor suite available in spidermon.
=> feature: Item validation built in monitor

tests/contrib/scrapy/test_pipelines.py, tests/test_spidermon_signal_connect.py
As Spidermon supports only Python versions greater than 3.5. It is not necessary to have this decorator over the tests as they will never be executed in older Python versions anymore.
=> chore: Remove test decorator that skips tests if executed in old Python versions

docs/source/settings.rst, spidermon/contrib/scrapy/extensions.py, spidermon/utils/field_coverage.py, tests/test_add_field_coverage.py, tests/test_item_scraped_signal.py, tests/test_spidermon_signal_connect.py, tests/utils/test_field_coverage.py
After this PR is merged, it will be easier to implement #253 as a new built-in monitor for field coverage.
When `SPIDERMON_ADD_FIELD_COVERAGE` is enabled, it will include a new set of stats containing information about field coverage for different item types, making it possible to use these stats in custom monitors.
=> feature: Add field coverage statistics

.travis.yml, README.rst, requirements.txt, setup.py, tox.ini
This PR solves #266 
I didn't find any code that is only used for Python 3.5, so just removing it from setup, documentation and CI settings should be enough.
=> Drop official support for Python 3.5

spidermon/contrib/scrapy/pipelines.py, spidermon/contrib/stats/counters.py
```
/home/travis/build/scrapinghub/spidermon/spidermon/contrib/stats/counters.py:40: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
class DictPercentCounter(PercentCounterBase, collections.MutableMapping):
...
/home/travis/build/scrapinghub/spidermon/spidermon/contrib/scrapy/pipelines.py:144: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
data = json.loads(to_native_str(serialized_json.getvalue(), exporter.encoding))
```
https://travis-ci.org/github/scrapinghub/spidermon/jobs/725926867#L289
https://travis-ci.org/github/scrapinghub/spidermon/jobs/725926867#L305
=> chore: Fix deprecation warnings

spidermon/core/suites.py
Similar to https://github.com/scrapinghub/spidermon/commit/19ce468121bee449c486c4adf9a4be96226af6a3
=> chore: Fix warning regarding ABC import from collections

tests/test_add_field_coverage.py, tests/test_item_scraped_signal.py
This PR will remove `PytestCollectionWarning` raised every time we run
the tests. This was happening because we have some test classes (thar
are not tests) trying to be collected by pytest.
=> chore: Fix warnings when running tests

docs/source/item-validation.rst
This happened in a real project. I enabled this pipeline, but added subsequent pipelines that changed the content of a valid item to an invalid content. This left me with an invalid item, but no validation error was raised. Adding this warning should prevent this kind of error (for the ones that read the docs :smile: ).
=> docs: Add warning regarding execution order of item validation pipeline

spidermon/contrib/validation/schematics/translator.py
Schematics 2.1.1 changed the [error message](https://github.com/schematics/schematics/commit/787c7f27acee37a85c6a9eda6eb53a19cd38c89a#diff-e6a5aa2776fcdc843a6af32fdefdb50ef37ece6ab470f1c4ab1580aecd61a418L168) when a value doesn't match one of the available choices of a field.
This commit updates the regex used to identify this message, so it continues being translated to the common `messages.VALUE_NOT_IN_CHOICES` that is shared amongst all validator libraries.
=> Update translation regex to identify new schematics message

docs/source/monitors.rst, spidermon/contrib/scrapy/monitors.py, spidermon/results/monitor.py, tests/contrib/scrapy/monitors/test_base_stat_monitor.py
Solves #321 
This PR includes a easier way to create custom monitors based on simple comparisons between a job stat and a threshold. We are talking usually about numerical values, but for EQUAL and NOTEQUAL, this can be strings as well.
A monitor that checks if a stat called `test_stat` is greater than or equal to a value defined in a project setting called `TEST_STAT_THRESHOLD`can be defined as follows:
```
class TestStatMonitor(BaseStatMonitor):
stat_name = "test_stat"
threshold_setting = "TEST_STAT_THRESHOLD"
assert_type = AssertionType.GTE
```
The threshold value can also be defined by a method, so we are able to create more complex rules to define what the threshold should be. Some ideas that can be accomplished using that method:
* Compare the number of items returned with the …
=> Create Base Stat Monitor class to help creating custom monitors

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/monitors/test_item_count_monitor.py
Use the new `BaseStatMonitor` to implement Item Count Monitor
=> Use BaseStatMonitor to implement built-in item count monitor

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/monitors/test_periodic_execution_time_monitor.py
Fixing issue where it checks unix timestamp instead of datetime retrieved via utcnow. Reported in original PR after merge - https://github.com/scrapinghub/spidermon/pull/309
=> [PeriodicExecutionTimeMonitor] Using utcnow and comparing to spider start as dt

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/monitors/test_downloader_exception_monitor.py
All built-in monitors should use `BaseStatMonitor` when possible. So this PR will continue converting them. Also improving the documentation with a bit more details about the monitor.
=> Use BaseStatMonitor to implement built-in downloader exception monitor

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/monitors/test_downloader_exception_monitor.py
Fixed documentation and add test for the scenario when the stat is not available because no exception was raised. Also fixed a missing white space that made the error message has two strings concatenated.
=> Skipped monitor for downloader exception

spidermon/contrib/scrapy/extensions.py, spidermon/utils/hubstorage.py
=> Fix "ModuleNotFoundError" when running spider outside Scrapy Cloud

docs/source/conf.py
Introduced in Sphinx 5.x:
https://github.com/sphinx-doc/sphinx/issues/10062
We need to define a language in our conf.py
=> Fix Sphinx 5 warning by setting docs language

spidermon/contrib/actions/discord/__init__.py, spidermon/contrib/actions/email/__init__.py, spidermon/contrib/actions/email/ses.py, spidermon/contrib/actions/reports/__init__.py, spidermon/contrib/actions/reports/files.py, spidermon/contrib/actions/reports/s3.py, spidermon/contrib/actions/sentry/__init__.py, spidermon/contrib/actions/slack/__init__.py, spidermon/contrib/actions/telegram/__init__.py
Improve messages making clear which setting should be defined to configure the failing action. This will help the users of the extension to easily identify how to configure the mandatory settings.
=> Improve not configured exception messages

.github/workflows/main.yml, docs/source/howto/configuring-telegram-for-spidermon.rst, requirements.txt, setup.py, spidermon/contrib/validation/jsonschema/formats.py, spidermon/contrib/validation/jsonschema/translator.py, tests/test_validators_jsonschema.py, tox.ini
I have managed to pass the tests after updating jsonschema. The only issue I have is that Python 3.6 is having dependency issues with jsonschema==4.
I'll try to make the changes compatible with both jsonschema4 and 3, so that Python3.6 is still compatible.
=> Fix compatibility issues with jsonschema>=4

docs/source/monitors.rst
Added new battery PeriodicExecutionTimeMonitor to  the sphinx member list.
=> Adding PeriodicExecutionTimeMonitor to the batteries docs

.github/workflows/main.yml, .github/workflows/publish.yml
Our pipeline hasn't been running for Python 3.6. This is due to an issue with github actions (https://github.com/actions/setup-python/issues/544). Fixing the ubuntu version to 20.04 should fix the problem according to the comments.
=> Change Ubuntu version on workflow settings.

spidermon/contrib/scrapy/monitors.py, tests/contrib/scrapy/monitors/test_base_stat_monitor.py
Fixes #374.
When reading threshold values from the settings, the `BaseStatMonitor` [used ](https://github.com/scrapinghub/spidermon/pull/325/files#diff-9d830f5588694dea71ec34a158727c22a20d77630f7d8afd1705d966241ab00dR123) the `settings.get()` function. This works fine if the value is set in the project's settings as the data type is preserved when reading it. However, when getting the settings from a Scrapy Cloud project, using the bare `get()` function causes the value to be read as a string, which break comparisions.
The monitor was updated to use by default the `getfloat` function. A variable was added which allows setting the threshold data type (either `int` or `float`) along with a property that picks the correct _get_ function depending on the data type.
Two new unit tests were …
=> Update `BaseStatMonitor`'s `test_stat_monitor` to work with Scrapy Cloud

spidermon/contrib/scrapy/monitors/monitors.py, tests/contrib/scrapy/test_monitors_field_coverage.py
Closes #366 
Added another setting called `SPIDERMON_FIELD_COVERAGE_SKIP_IF_NO_ITEM` for `FieldCoverageMonitor`:
- If this setting is enabled and we don't have any items scraped, it will not raise error anymore, it will send a message instead.
=> Allow to skip execution of FieldCoverageMonitor if no item is returned

spidermon/contrib/scrapy/extensions.py, spidermon/contrib/scrapy/monitors/monitors.py, spidermon/utils/zyte.py, tests/contrib/scrapy/monitors/test_jobs_comparison_monitor.py, tests/utils/test_zyte.py
Fixes https://github.com/scrapinghub/spidermon/issues/410
=> Refactor spidermon.utils.zyte.Client to use crawler settings

tests/contrib/validation/test_item_validation_pipeline.py
The current spidermon behavior for adding `_validation` field to items seems to be a bit controversial: https://github.com/scrapinghub/spidermon/issues/379
To make easier to track changes, I have implemented some additional tests that covers the current logic.
=> Add tests for item validation pipeline

docs/source/item-validation.rst, spidermon/contrib/scrapy/pipelines.py, spidermon/contrib/utils/attributes.py, tests/contrib/scrapy/test_pipelines.py, tests/contrib/utils/test_attributes.py
Allows to use a nested field as validation field. Nested fields are supported by using `.` separator:
```python
SPIDERMON_VALIDATION_ERRORS_FIELD = "top_level.second_level._validation"
```
=> Add support for nested fields in SPIDERMON_VALIDATION_ERRORS_FIELD

conftest.py, tests/contrib/scrapy/monitors/conftest.py
**Overview**
This PR fixes the broken CI in `master`.
**Background**
The latest Scrapy versions don't have their StatsCollector (`crawler.stats`) initialized when a crawler is created. Tests that expect it to be there fail otherwise.
**Fix**
This was fixed by manually initializing `crawler.stats` the same way this was fixed in https://github.com/scrapinghub/scrapy-poet/pull/165
=> Fixes #422

docs/source/getting-started.rst, docs/source/item-validation.rst, spidermon/contrib/scrapy/pipelines.py, tests/contrib/validation/test_item_validation_pipeline.py
The content of _validation field must to be the string representation of a Python dict instead defaultdict when SPIDERMON_VALIDATION_ADD_ERRORS_TO_ITEMS setting is True.
=> Change format of content of _validation field (#425)

spidermon/utils/field_coverage.py, tests/utils/test_field_coverage.py
Fixes https://github.com/scrapinghub/spidermon/issues/428
It only cover the case where the fields ends with "_items" but is prefixed with something else like "count_items". 
Using only `_items` as field name is still not compatible with the coverage count. We may be able to make it work but it would require a significant rewrite of `calculate_field_coverage`
=> Fix Field names containing '_items' crash field coverage

spidermon/contrib/scrapy/monitors/monitors.py, spidermon/core/monitors.py
- Add utc_now_with_timezone method in base monitor class
- Modify PeriodicExecutionTimeMonitor with the above method usage
Fixes https://github.com/scrapinghub/spidermon/issues/438
=> [spidermon] Fix subtract offset-naive and offset-aware

spidermon/contrib/scrapy/monitors/monitors.py, tests/contrib/scrapy/monitors/test_jobs_comparison_monitor.py, tox.ini
Fixes https://github.com/scrapinghub/spidermon/issues/442
=> Fix get_jobs method in Comparison Monitor

spidermon/contrib/scrapy/monitors/monitors.py, tests/contrib/scrapy/monitors/test_jobs_comparison_monitor.py
Fixes https://github.com/scrapinghub/spidermon/issues/445
=> Fixes Scrapinghub jobs.list Method Called with Incorrect Filter Parameter

docs/source/settings.rst, spidermon/contrib/scrapy/monitors/base.py
Fixes https://github.com/scrapinghub/spidermon/issues/430
=> Add SPIDERMON_MONITOR_SKIPPING_RULES docs to settings

spidermon/contrib/actions/discord/templates/discord/spider/notifier/macros.jinja, spidermon/contrib/actions/reports/templates/reports/email/monitors/result.jinja, spidermon/contrib/actions/slack/templates/slack/spider/notifier/macros.jinja, spidermon/contrib/actions/telegram/templates/telegram/spider/notifier/macros.jinja, tests/contrib/actions/jobs/test_tags.py
Replaces all instances of `data.job.metadata[x]` in the templates with `data.job.metadata.get(x)`.
=> [429] Fix default templates non-subscriptable problem

.github/workflows/main.yml
For some reason, codecov was not working with the previous version.
=> Update codecov action

spidermon/contrib/actions/sentry/__init__.py
Sentry groups issues by the provided message argument in the implemented scenario. However, when the message includes a pattern recognizable by sentry defined here - https://github.com/getsentry/sentry/blob/master/src/sentry/grouping/parameterization.py#L56, values against these patterns are replaced with placeholders and aren't used to group issues.
E.g., if the sentry title contains hostnames with the same exception, the two would be grouped as below
Prashant Test Local | Development | Spider bookspider.com notification
Prashant Test Local | Development | Spider quotespider.com notification
grouped into
Prashant Test Local | Development | Spider `<hostname>` notification
This would be unintended behaviour, and we'd like to have the two spiders raise two different sentry alerts. …
=> [actions][sentry] apply fingerprint rules to group issues better
