docs/source/item-validation.rst
spidermon/contrib/validation/jsonschema/formats.py
spidermon/contrib/validation/jsonschema/validator.py

Infer validator class based on given schema

---

.travis.yml

Just a little update to simplify .travis.yml

Add tox-travis to simplify matrix

---

setup.py

Used by PythonExpressionsMonitor (https://github.com/scrapinghub/spidermon/blob/master/spidermon/python/factory.py#L34)

Included jsonschema as required dependency

---

spidermon/contrib/validation/schematics/validator.py
spidermon/contrib/validation/translator.py
tests/test_validators_schematics.py

Schematics model level validation

---

docs/source/installation.rst

Update note about dependencies

---

docs/source/actions.rst

This PR updated an action example.

Fix SendSESEmail action documentation

---

spidermon/contrib/actions/email/__init__.py
spidermon/contrib/actions/sentry/__init__.py
spidermon/contrib/actions/slack/__init__.py

This implements the feature #102

Replace print on actions with logging library

---

docs/source/monitors.rst
docs/source/settings.rst
examples/tutorial/tutorial/actions.py
examples/tutorial/tutorial/monitors.py
examples/tutorial/tutorial/settings.py

[MRG +1] Periodic monitors docs

---

CONTRIBUTING.rst
docs/source/conf.py
docs/source/monitors.rst

We had an issue when building the docs using `make html` because it wasn't creating autodocs from docstrings.
I updated `conf.py` to include a path to spidermon.
Also updated the contributing guide adding the commands to build the docs.

Improving docs

---

spidermon/contrib/scrapy/monitors.py
tests/test_monitors.py

Issue:
https://github.com/scrapinghub/spidermon/issues/153

Added New Setting "SPIDERMON_UNWANTED_HTTP_CODES_THRESHOLD" [#153]

---

.travis.yml

@Gallaecio continuing the discussion of PR #206 here, with a proper PR.
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

ci: Enforce Black formatting through pipelines

---

README.rst

Fixed build badge to show status only of master branch

---

.travis.yml
setup.py
tox.ini

- Removed Python 3.4 from Travis
- Removed pinned requirements specific to Python 3.4

feature: Dropped python 3.4 support

---

.travis.yml
tox.ini

:hatching_chick: Solves #169
Some info on options selected, 
`-n`  is to get all the warnings (Be nit-picky)
`-W` is to turn warning into errors
Also, added link-checking as well. Figure it would help in the long run. 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

ci: Validate docs build in CI

---

spidermon/contrib/actions/slack/__init__.py
tests/contrib/actions/slack/test_slack_message_manager.py

feature: Allowed to define SPIDERMON_SLACK_RECIPIENTS setting as a comma-separated string with the desired recipients.

---

CONTRIBUTING.rst
docs/source/configuring-slack-for-spidermon.rst
docs/source/configuring-telegram-for-spidermon.rst

Updated docs removing hard-coded enumerations in favour of auto-enumerated markup.
This remove the need to update all numbers if we include extra items to lists.

docs: Updated enumerated lists with auto-enumerated markup

---

requirements.txt
setup.py
spidermon/contrib/scrapy/monitors.py
tests/contrib/monitors/mixins/test_validation.py
tests/contrib/scrapy/test_item_validation_monitor.py

Fix this build:
https://travis-ci.org/github/scrapinghub/spidermon/jobs/689622501

Reformat code with black to fix failed build

---

.travis.yml
README.rst
requirements.txt
setup.py
spidermon/contrib/scrapy/monitors.py
spidermon/python/interpreter.py
spidermon/results/monitor.py
spidermon/utils/hubstorage.py
tests/contrib/monitors/mixins/test_validation.py
tests/contrib/scrapy/test_item_validation_monitor.py
tests/fixtures/expressions.py
tox.ini

chore: Removed Python 2.7 support

---

README.rst
setup.py
spidermon/python/interpreter.py
tox.ini

chore: Add Python 3.8 support

---

spidermon/contrib/actions/sentry/__init__.py
spidermon/contrib/monitors/mixins/validation.py
tests/contrib/scrapy/test_monitors_field_coverage.py
tests/test_add_field_coverage.py
tests/test_item_scraped_signal.py
tests/test_monitors.py

Build was failing because code wasn't formatted accordingly using black.

Fix code formatting with black

---

docs/source/howto/stats-collection.rst
docs/source/item-validation.rst
docs/source/monitors.rst
docs/source/settings.rst

This PR solves conflict problems with
https://github.com/scrapinghub/spidermon/pull/199

docs: Fixed inconsistent examples

---

docs/source/actions.rst
docs/source/getting-started.rst
requirements.txt
setup.py
spidermon/contrib/actions/slack/__init__.py
tests/contrib/actions/slack/test_slack_action.py
tests/contrib/actions/slack/test_slack_message_manager.py

This PR fixes https://github.com/scrapinghub/spidermon/issues/251
Updating the slackclient to the new version.
Requirements and setup were updated to use slackclient versions higher than 2.0.
I also updated tests and docs.

Update slackclient to v2.0

---

setup.py
spidermon/contrib/actions/email/ses.py

Fixes #285
Based on https://stackoverflow.com/a/52105406/939364
I still need to test this (manually).

spidermon.contrib.actions.email.ses: switch to boto3

---

docs/source/howto/stats-collection.rst
examples/tutorial/tutorial/settings.py
spidermon/contrib/stats/statscollectors/__init__.py
spidermon/contrib/stats/statscollectors/local_storage.py
spidermon/contrib/stats/statscollectors/sc_collections.py
tests/contrib/stats/statscollectors/test_local_storage.py
tests/contrib/stats/statscollectors/test_sc_collections.py

Refactor stats collectors

---

docs/source/actions/email-action.rst
spidermon/contrib/actions/email/__init__.py
spidermon/contrib/actions/email/ses.py
spidermon/contrib/actions/email/smtp.py
tests/contrib/actions/email/email/test_smtp_email.py

Adding the support for SMTP email support

Added SMTP email support

---

setup.py

Fixes https://github.com/scrapinghub/spidermon/issues/363

Fix slack dependency name issue

---

.github/workflows/main.yml
.pre-commit-config.yaml
setup.py
spidermon/contrib/actions/sentry/__init__.py
spidermon/contrib/monitors/mixins/validation.py
spidermon/contrib/scrapy/monitors.py
spidermon/contrib/validation/translator.py
spidermon/python/interpreter.py
spidermon/results/text.py
tests/contrib/scrapy/test_extensions.py
tests/contrib/scrapy/test_pipelines.py
tests/fixtures/items.py
tests/test_add_field_coverage.py
tests/test_item_scraped_signal.py
tox.ini

Fix https://github.com/scrapinghub/spidermon/issues/385

Replace tox pep8 with pre-commits rules and pipeline

---

.readthedocs.yaml
requirements-docs.txt

Addresses https://github.com/scrapinghub/spidermon/issues/405

Migrates ReadTheDocs to config file v2
